language: cpp

script: 
 - mv ./tools/filechars.cpp ./filechars.cpp
 - mv ./include/qmus2mid/qmus2mid.cpp ./qmus2mid.cpp
 - mv ./include/qmus2mid/qmus2mid.h ./include/qmus2mid.h
 - mv ./src/unwad.cpp ./unwad.cpp
 - mv ./lib/libmagic.dll.a ./lib/libmagic.a
 - mv ./lib/libpng.dll.a ./lib/libpng.a
 - mv ./lib/libregex.dll.a ./lib/libregex.a
 - mv ./lib/libz.dll.a ./lib/libz.a
# - mkdir /usr/lib/
# - mv ./lib/*.dll.a /usr/lib/
 - sh build.sh
